name: CI

on:
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 21 * * *"

jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Format
        run: crystal tool format --check
  coding_standards:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: shards install
      - name: Ameba
        run: ./bin/ameba

  test_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        run: |
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt install nodejs
          npm i -g npx
      - name: Install Crystal
        run: |
          sudo snap install crystal --classic
          sudo apt -y install libssl-dev libxml2-dev libyaml-dev libgmp-dev libreadline-dev libz-dev libevent-dev gcc pkg-config tzdata libpcre3-dev
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: shards install
      - name: Specs
        run: crystal spec --order random --error-on-warnings

  test_nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        run: |
          curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
          sudo apt install nodejs
          npm i -g npx
      - name: Install Crystal
        run: |
          sudo snap install crystal --classic --edge
          sudo apt -y install libssl-dev libxml2-dev libyaml-dev libgmp-dev libreadline-dev libz-dev libevent-dev gcc pkg-config tzdata libpcre3-dev
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: shards install
      - name: Specs
        run: crystal spec --order random --error-on-warnings
